// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBptP6EiuxgLprEMDAyDDVhwtTs3-JW4bY',
    appId: '1:848529697826:web:9c4e050ed7ddafb08cae7b',
    messagingSenderId: '848529697826',
    projectId: 'invest-f173c',
    authDomain: 'invest-f173c.firebaseapp.com',
    storageBucket: 'invest-f173c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALKlUsSDCi3uElKP9HU4OwkMlXrgOY8B4',
    appId: '1:848529697826:android:2868c30a2b4c64f18cae7b',
    messagingSenderId: '848529697826',
    projectId: 'invest-f173c',
    storageBucket: 'invest-f173c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdi6lEoLp0MFJFvwG_BqnhC6cRenF98Rs',
    appId: '1:848529697826:ios:4893f0b172c805db8cae7b',
    messagingSenderId: '848529697826',
    projectId: 'invest-f173c',
    storageBucket: 'invest-f173c.appspot.com',
    androidClientId: '848529697826-6hrov979bjluudmiuiblr8he7ni0ajfg.apps.googleusercontent.com',
    iosClientId: '848529697826-ijb0ancaibi67v42621u0a6b0r19disj.apps.googleusercontent.com',
    iosBundleId: 'com.investanchors.investor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdi6lEoLp0MFJFvwG_BqnhC6cRenF98Rs',
    appId: '1:848529697826:ios:f56ca80316e2d4b78cae7b',
    messagingSenderId: '848529697826',
    projectId: 'invest-f173c',
    storageBucket: 'invest-f173c.appspot.com',
    androidClientId: '848529697826-6hrov979bjluudmiuiblr8he7ni0ajfg.apps.googleusercontent.com',
    iosClientId: '848529697826-b3aa573r6ebmks4erjrm3ffvubqsn19j.apps.googleusercontent.com',
    iosBundleId: 'com.example.invest',
  );
}
